CREATE TABLE GENAWS_TB_PROFESSOR (
    ID BIGSERIAL PRIMARY KEY,
    NOME_PROFESSOR VARCHAR(100) NOT NULL,
    IS_ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE GENAWS_TB_ALUNO (
    ID BIGSERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    IDADE BIGINT NOT NULL,
    NOTA_PRIMEIRO_SEMESTRE BIGINT,
    NOTA_SEGUNDO_SEMESTRE BIGINT,
    IS_ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE GENAWS_TB_SALA (
    ID BIGSERIAL PRIMARY KEY,
    NUMERO_SALA BIGINT,
    IS_ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE GENAWS_ALUNO_SALA (
    aluno_id INT REFERENCES GENAWS_TB_ALUNO(id),
    sala_id INT REFERENCES GENAWS_TB_SALA(id),
    PRIMARY KEY (aluno_id, sala_id)
);

CREATE TABLE GENAWS_ALUNO_PROFESSOR (
    aluno_id INT REFERENCES GENAWS_TB_ALUNO(id),
    professor_id INT REFERENCES GENAWS_TB_PROFESSOR(id),
    PRIMARY KEY (aluno_id, professor_id)
);

CREATE TABLE GENAWS_SALA_PROFESSOR (
    sala_id INT REFERENCES GENAWS_TB_SALA(id),
    professor_id INT REFERENCES GENAWS_TB_PROFESSOR(id),
    PRIMARY KEY (sala_id, professor_id)
);
